#!/bin/bash
#
# Check if node is actively validating given a hex. session keys
#
# The script checks if the provided session keys are in use
# and returns true or false 
#
# Author: Derfredy | @derfredy:matrix.org
#

LAST_KEY=`cat lastkeys.log`

curl --silent --location --request POST 'http://localhost:9933' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "author_hasSessionKeys",
    "params": ["'"$LAST_KEY"'"],
    "id": 1
}' | jq
